# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.navigationBar = QtWidgets.QLineEdit(self.centralwidget)
        self.navigationBar.setObjectName("navigationBar")
        self.gridLayout_2.addWidget(self.navigationBar, 0, 1, 1, 1)
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setObjectName("goButton")
        self.gridLayout_2.addWidget(self.goButton, 0, 2, 1, 1)
        self.folderWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.folderWidget.setMinimumSize(QtCore.QSize(0, 291))
        self.folderWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.folderWidget.setObjectName("folderWidget")
        self.folderWidget.setColumnCount(4)
        self.folderWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.folderWidget.setHorizontalHeaderItem(3, item)
        self.folderWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.folderWidget.horizontalHeader().setDefaultSectionSize(150)
        self.folderWidget.horizontalHeader().setMinimumSectionSize(19)
        self.folderWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.folderWidget, 1, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.tasksWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tasksWidget.setObjectName("tasksWidget")
        self.tasksWidget.setColumnCount(5)
        self.tasksWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tasksWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tasksWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tasksWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tasksWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tasksWidget.setHorizontalHeaderItem(4, item)
        self.tasksWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tasksWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tasksWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tasksWidget)
        self.gridLayout_3.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.ipInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ipInput.setObjectName("ipInput")
        self.gridLayout.addWidget(self.ipInput, 0, 1, 1, 1)
        self.userInput = QtWidgets.QLineEdit(self.centralwidget)
        self.userInput.setObjectName("userInput")
        self.gridLayout.addWidget(self.userInput, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.portInput = QtWidgets.QLineEdit(self.centralwidget)
        self.portInput.setObjectName("portInput")
        self.gridLayout.addWidget(self.portInput, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.gridLayout.addWidget(self.passwordInput, 0, 7, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 0, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPassive = QtWidgets.QAction(MainWindow)
        self.actionPassive.setObjectName("actionPassive")
        self.actionPort = QtWidgets.QAction(MainWindow)
        self.actionPort.setObjectName("actionPort")
        self.actionSystem = QtWidgets.QAction(MainWindow)
        self.actionSystem.setObjectName("actionSystem")
        self.actionType = QtWidgets.QAction(MainWindow)
        self.actionType.setObjectName("actionType")
        self.actionNew_folder = QtWidgets.QAction(MainWindow)
        self.actionNew_folder.setObjectName("actionNew_folder")
        self.actionPut_file = QtWidgets.QAction(MainWindow)
        self.actionPut_file.setObjectName("actionPut_file")
        self.actionMax_Occurs = QtWidgets.QAction(MainWindow)
        self.actionMax_Occurs.setObjectName("actionMax_Occurs")
        self.actionPut_folder = QtWidgets.QAction(MainWindow)
        self.actionPut_folder.setObjectName("actionPut_folder")
        self.menuSetting.addAction(self.actionPassive)
        self.menuSetting.addAction(self.actionPort)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionMax_Occurs)
        self.menuHelp.addAction(self.actionSystem)
        self.menuHelp.addAction(self.actionType)
        self.menuFile.addAction(self.actionNew_folder)
        self.menuFile.addAction(self.actionPut_file)
        self.menuFile.addAction(self.actionPut_folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.goButton.setText(_translate("MainWindow", "Go"))
        item = self.folderWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.folderWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.folderWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.folderWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tasksWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tasksWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Local File"))
        item = self.tasksWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Remote File"))
        item = self.tasksWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tasksWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Progress"))
        self.label_3.setText(_translate("MainWindow", "User"))
        self.ipInput.setText(_translate("MainWindow", "0.0.0.0"))
        self.userInput.setText(_translate("MainWindow", "anonymous"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.portInput.setText(_translate("MainWindow", "21"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.passwordInput.setText(_translate("MainWindow", "ddd"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionPassive.setText(_translate("MainWindow", "Passive"))
        self.actionPort.setText(_translate("MainWindow", "Port"))
        self.actionSystem.setText(_translate("MainWindow", "System"))
        self.actionType.setText(_translate("MainWindow", "Type"))
        self.actionNew_folder.setText(_translate("MainWindow", "New folder"))
        self.actionPut_file.setText(_translate("MainWindow", "Put file"))
        self.actionMax_Occurs.setText(_translate("MainWindow", "Max Occurs"))
        self.actionPut_folder.setText(_translate("MainWindow", "Put folder"))

